In [2]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


In [5]:
# Array Sum
array_2 = np.array([5, 4, 3, 2, 1])

print(array + array_2)

[6 6 6 6 6]


In [8]:
# Matrix Product
matrix = np.array([[1, 2], [2, 1]])
matrix_2 = np.array([[3, 1], [2, 3]])

print(np.dot(matrix, matrix))
print(np.dot(matrix, matrix_2))

[[5 4]
 [4 5]]
[[7 7]
 [8 5]]
